/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Laundry;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hanjian Listanto
 */
public class Pengambilan extends javax.swing.JDialog {

    /**
     * Creates new form Pengambilan
     */
    public Pengambilan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        namaInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        ambilButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        keluarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tgl Pemesanan", "Nama", "No Telepon", "Paket", "Berat (kg)", "Harga (kg)", "Total Harga"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        namaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namaInputKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Nama Pelanggan");

        head.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        head.setText("PENGAMBILAN");

        ambilButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ambilButton.setText("Ambil");
        ambilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambilButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        keluarButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        keluarButton.setText("Keluar");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keluarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ambilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(head)
                .addGap(360, 360, 360))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(head)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ambilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(keluarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String Nama;
    int hargaTotal;

    public void showData() {
        Koneksi p = new Koneksi();
        Connection conn = null;

        Statement st = null;
        ResultSet rs = null;

        conn = p.getConnection();
        DefaultTableModel Data = (DefaultTableModel) jTable1.getModel();
        Data.setRowCount(0);
        try {
            st = conn.createStatement();
            rs = st.executeQuery("select * from pemesan");

            while (rs.next()) {
                String tglPemesan = rs.getString(1);
                Nama = rs.getString(2);
                String telepon = rs.getString(3);
                String paket = rs.getString(4);
                int berat = rs.getInt(5);
                int harga = rs.getInt(6);
                int hargaTotal = rs.getInt(7);
                
                Data.addRow(new Object[]{tglPemesan, Nama, telepon, paket, berat, harga, hargaTotal});

            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            try {
                rs.close();
                st.close();
                conn.close();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }

    }

    private void ambilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambilButtonActionPerformed
        Koneksi p = new Koneksi();
        Connection conn = null;
        PreparedStatement ps = null;
        conn = p.getConnection();

        if (namaInput.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Pastikan teks sudah terisi");
        } else {
            int option = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data " + namaInput.getText() + " ?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                try {
                    conn.setAutoCommit(false);
                    ps = conn.prepareStatement("DELETE FROM pemesan WHERE nama = ?");
                    ps.setObject(1, namaInput.getText());

                    int n = ps.executeUpdate();
                    resetText();
                    if (n < 1) {
                        throw new SQLException("Data tidak tersedia.");
                    }
                    conn.commit();
                    showData();

                    System.out.println(n + " terekam");
                    JOptionPane.showMessageDialog(null, "Data " + namaInput.getText() + " berhasil dihapus", "Data terhapus", JOptionPane.INFORMATION_MESSAGE);

                } catch (SQLException ex) {
                    System.err.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Terjadi kesalahan. Silahkan cek kembali Nama yang tersedia", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                }
            }
        }


    }//GEN-LAST:event_ambilButtonActionPerformed

    public void resetText() {
        namaInput.setText(null);
    }

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        namaInput.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_keluarButtonActionPerformed

    private void namaInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaInputKeyPressed

    }//GEN-LAST:event_namaInputKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengambilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengambilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengambilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengambilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pengambilan dialog = new Pengambilan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambilButton;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluarButton;
    private javax.swing.JTextField namaInput;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
